USE FondoAhorrosDB;

CREATE PROCEDURE FASP_InsertarDeudores
	@pNombre VARCHAR(100) = NULL,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.Deudores(Nombre)
			VALUES (@pNombre)
		COMMIT TRANSACTION;

		RETURN SCOPE_IDENTITY();

	END TRY
	BEGIN CATCH	
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_InsertarPrestamo
	@pMontoOriginal INT = 0,
	@pCuota INT = 0,
	@pPlazoRestante INT = 0,
	@pDiaCorte = 0,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.Prestamos(MontoOriginal, Cuota, PlazoRestante, SaldoNoAplicado, SaldoAplicado, InteresAcumulado, DiaCorte)
			VALUES (@pMontoOriginal, @pCuota, @pPlazoRestante, 0, 0, 0 @pDiaCorte)
		COMMIT TRANSACTION;

		RETURN SCOPE_IDENTITY();
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_InsertarMovimientoInteresDiario
	@pFecha DATE = NULL,
	@pMonto INT = 0,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.MovimientoInteresDiario(Fecha, Monto)
			VALUES (@pFecha, @pMonto)
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_InsertarMovimientoSaldoNoAplicado
	@pFecha DATE = NULL,
	@pAmortizacion INT = 0,
	@pIntereses INT = 0,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.MovimientoSaldoNoAplicado(Fecha, Amortizacion, Interes)
			VALUES (@pFecha, @pAmortizacion, @pInteres)
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_InsertarMovimientoSaldoAplicado
	@pFecha DATE = NULL,
	@pAmortizacion INT = 0,
	@pInteres INT = 0,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.MovimientoSaldoAplicado(Fecha, Amortizacion, Interes)
			VALUES(@pFecha, @pAmortizacion, @pIntereses)
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_TipoMovimientoInteresDiario
	@pNombre VARCHAR(100),

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.TipoMovimientoInteresDiario(Nombre)
			VALUES(@pNombre)
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_TipoPrestamo
	@pNombre VARCHAR(100) = NULL,
	@pTasa INT = 0,
	@pPlazo INT = 0,
	@pPeriodo INT = 0;

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.TipoPrestamo(Nombre, Tasa, Plazo, Periodo)
			VALUES (@pNombre, @pTasa, @pPlazo, @pPeriodo)
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK

		RETURN @@ERROR * -1;
	END CATCH
END
GO