USE FondoAhorrosDB;

CREATE PROCEDURE FASP_InsertarDeudores
	@pNombre VARCHAR(100) = NULL,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.Deudores(Nombre)
			VALUES (@pNombre)
		COMMIT TRANSACTION;

		RETURN SCOPE_IDENTITY();

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_InsertarPrestamo
	@pMontoOriginal INT = 0,
	@pCuota INT = 0,
	@pPlazoRestante INT = 0,
	@pDiaCorte = 0,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.Prestamos(MontoOriginal, Cuota, PlazoRestante, SaldoNoAplicado, SaldoAplicado, InteresAcumulado, DiaCorte)
			VALUES (@pMontoOriginal, @pCuota, @pPlazoRestante, 0, 0, 0 @pDiaCorte)
		COMMIT TRANSACTION;

		RETURN SCOPE_IDENTITY();
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO

CREATE PROCEDURE FASP_InsertarMovimientoInteresDiario
	@pFecha DATE = NULL,
	@pMonto INT = 0,

AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		BEGIN TRANSACTION;
			INSERT INTO dbo.MovimientoInteresDiario(Fecha, Monto)
			VALUES (@pFecha, @pMonto)
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK;

		RETURN @@ERROR * -1;
	END CATCH
END
GO
